name:                leetcode
version:             0.1.0.0
github:              "zcesur/leetcode"
license:             GPL-3
author:              "Zafer Cesur"
maintainer:          "17045339+zcesur@users.noreply.github.com"
copyright:           "2020 Zafer Cesur"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zcesur/leetcode#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- unordered-containers
- array
- mtl
- hashable
- fgl

library:
  source-dirs: src
  ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

tests:
  leetcode-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - leetcode
    - hspec
    - hspec-discover
    - array
    - mtl
